spring:
  profiles:
    active:
    - dev
    
---

server:
  port: 8206

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eruka/
   
---
server:
  port: 8204
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eruka/
   